### ISSUE TITLE
64bit Linuxでのビルドについて

### ISSUE THREAD

**Issue by sksat** [HariboteOS/tolsrc#1]
64bit Linux（僕の場合はUbuntu 16.04）でコンパイルしようとすると、sys/cdefs.hが見つからず、失敗します。
```apt-get install libc6-dev-i386```
とすると、コンパイルが通るようになるので、READMEなどに注意があるといいかもしれません。

**Comment by hikalium** [comment]
遅くなってごめんなさい．ご報告ありがとうございます．
```
apt-get install libc6-dev-i386
apt-get install g++
```
私の環境では上記が必要でしたので（まあ`g++`は自明ですが），READMEにその旨追加します．
